package botting.reflection.hooking;

public enum ClientHook {
    METHOD_MAIN,

    CLASS_MAIN,

    FIELD_MAIN_INSTANCE,

    CLASS_GAME_RENDER,

    FIELD_MOUSE_X,
    FIELD_MOUSE_Y,

    CLASS_CLIENT,

    FIELD_CLIENT_INSTANCE,

    FIELD_X_CAMERA_POS,
    FIELD_Y_CAMERA_POS,
    FIELD_Z_CAMERA_POS,

    FIELD_CAMERA_PITCH,
    FIELD_CAMERA_YAW,

    FIELD_TILE_OFFSETS,

    FIELD_SCENE_FLAGS,

    CLASS_ENTITY,

    FIELD_ENTITY_HEIGHT,

    CLASS_DEQUE,

    FIELD_GROUND_ITEMS_ARRAY,

    FIELD_DEQUE_CURRENT_NODE,

    CLASS_NODE,

    FIELD_NODE_NEXT,

    CLASS_PLAYER,

    CLASS_NPC,

    CLASS_NPC_DEFINITION,

    FIELD_NPC_ID,

    FIELD_MOB_DEF,

    FIELD_NPC_NAME,

    FIELD_ENTITY_ANIMATION,

    FIELD_PLAYER_ARRAY,

    FIELD_PLAYER_INSTANCE,

    FIELD_NPC_ARRAY,

    CLASS_ITEM,

    FIELD_GROUND_ITEM_ID,

    FIELD_GROUND_ITEM_AMOUNT,

    CLASS_RS_INTERFACE,

    FIELD_RS_INTERFACES_ARRAY,

    FIELD_RS_INTERFACE_INVENTORY,

    METHOD_NODE_UNLINK,

    FIELD_RIGHT_CLICK_MENU_DEQUE,

    CLASS_MENU_NODE,

    METHOD_DEQUE_GET_FIRST,

    METHOD_DEQUE_GET_NEXT,

    FIELD_IS_LOGGED_IN,

    FIELD_PLAYER_RIGHTS,

    FIELD_PLAYER_PASSWORD,
    FIELD_PLAYER_USERNAME,

    FIELD_Y_MENU_OFFSET,

    FIELD_INTERFACE_ID_OPEN,

    FIELD_ENTITY_X,
    FIELD_ENTITY_Y,

    FIELD_INTERACTING_ENTITY,

    FIELD_ENTITY_CURRENT_HEALTH,

    FIELD_BASE_X,
    FIELD_BASE_Y,

    FIELD_SKILL_XP_ARRAY,

    FIELD_SKILL_STAT_ARRAY,

    FIELD_PLANE,

    FIELD_PLAYER_INDEX,

    FIELD_CLIENT_ZOOM,

    CLASS_RIGHT_MENU,

    FIELD_HAS_MENU_OPEN,

    METHOD_KEY_PRESSED,

    METHOD_KEY_RELEASED,

    METHOD_MOUSE_WHEEL_MOVED,

    METHOD_MOUSE_PRESSED,

    METHOD_MOUSE_RELEASED,

    FIELD_MENU_ACTION_ROW, FIELD_MENU_WIDTH, FIELD_MENU_HEIGHT, FIELD_X_MENU_OFFSET, METHOD_REVERSE_GET_FIRST,

    FIELD_MENU_NODE_NAME, FIELD_EXTRA_MENU_NODE_NAME, FIELD_LOOP_CYCLE_STATUS, FIELD_LOOP_CYCLE, CLASS_CLIENT_DETAILS, FIELD_SCENE, FIELD_SCENE_TILES, CLASS_SCENE_TILE, FIELD_OBJECT_HASH, FIELD_SCENE_OBJECT_TILE, FIELD_OBJECT_X, FIELD_OBJECT_Y, FIELD_MINIMAP_ROTATION_VIEW, FIELD_MINIMAP_ROTATION, FIELD_MINIMAP_ZOOM, FIELD_DIALOG_OPEN_ID;
}



